### ISSUE TITLE
Add Types for Data

### ISSUE THREAD

**Issue by omervk** [ZuInnoTe/spark-hadoopcryptoledger-ds#10]
We should be able to use Spark 2.0's datasets to ease working with the data. Something along the lines of EthereumBlock and BitcoinBlock.

**Comment by jornfranke** [comment]
What do you mean? Yes this is what the data source provides ...

**Comment by omervk** [comment]
Functionality added by https://github.com/ZuInnoTe/spark-hadoopcryptoledger-ds/pull/11

**Comment by omervk** [comment]
@jornfranke Please see my pull request :)

**Comment by jornfranke** [comment]
Sorry was too fast I will check it later

**Comment by jornfranke** [comment]
will be part of 1.1.3

**Comment by jornfranke** [comment]
hmm the change breaks with Spark 1.5 compability and does not pass integration tests. At least for the integration tests we would need to compile it with Spark 2.0.1. I will check

**Comment by jornfranke** [comment]
i fixed it. I added for integration tests Spark 2.0.1 as a mandatory dependencies (we will make anyway Spark2 by next year mandatory together with scala 2.11 and JDK8).
Additionally, I copied the existing tests that you modified and added the description "with rich data types" (so they are still included and executed), but kept the old one. The reason is that i prefer to not modify tests that have been executed before successfully and add for new functionality new tests. I hope you do not mind. All your tests and your code anyway remained in the source and is executed.
